### ISSUE TITLE
Wenbank issue

### ISSUE THREAD

**Issue by SkullDynamo** [ayushbuai/Bankui#1]
PocketMine-MP Crash Dump Wed Jan 4 01:03:46 CST 2023

PocketMine-MP version: 4.12.1 [Protocol 560]
Git commit: 7ae6425d05cce581854f44c13845635f2ce0eef2
PHP version: 8.0.13
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: WenBank

Error: Call to undefined method pocketmine\Server::getPlayer()
File: plugins/Bankui-Bank/src/Biswajit/BankUI/BankUI
Line: 413
Type: Error
Backtrace:
#0 plugins/Bankui-Bank/src/Biswajit/BankUI/libs/jojoe77777/FormAPI/Form(46): Biswajit\BankUI\BankUI->Biswajit\BankUI\{closure}(object Stats\player\MagicPlayer#181239, array[3])
#1 pmsrc/src/player/Player(2049): Biswajit\BankUI\libs\jojoe77777\FormAPI\Form->handleResponse(object Stats\player\MagicPlayer#181239, array[3])
#2 pmsrc/src/network/mcpe/handler/InGamePacketHandler(866): pocketmine\player\Player->onFormSubmit(int 2, array[3])
#3 pmsrc/vendor/pocketmine/bedrock-protocol/src/ModalFormResponsePacket(63): pocketmine\network\mcpe\handler\InGamePacketHandler->handleModalFormResponse(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#223404)
#4 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\ModalFormResponsePacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#212681)
#5 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ModalFormResponsePacket#223404, string[26] e...[null,2,"101290192"]..)
#6 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[29] .Jeb...+...1.Q2404.40.4R..b..)
#7 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 2, string[38] .._./...S.........M']...|.......:...Q.)

**Comment by ayushbuai** [comment]
Transfer Poblam Will Be Fix In Next Update Soon .. Thanks For Issue

**Comment by ayushbuai** [comment]
Fixed At 1.1.0
